
DROP TABLE IF EXISTS RESTAURANT;


CREATE TABLE RESTAURANT (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(300) NOT NULL,
    LOCATION VARCHAR(300),
    CUISINE VARCHAR(100),
    SESSIONID VARCHAR(100),
    LOGGEDIN VARCHAR(10)
);
